apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-stack-grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/name: grafana
spec:
  ingressClassName: nginx
  rules:
  - host: grafana.sikiru.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-stack-grafana
            port:
              number: 80
