apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare # Re-use n8n issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "false"      # This is kept FALSE to avoid loops
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - longhorn.sikiru.co.uk
      secretName: longhorn-tls-cert
  rules:
    - host: longhorn.sikiru.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: longhorn-frontend
                port:
                  number: 80
